# Generated by Django 5.2.7 on 2025-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别'),
        ),
    ]
